package MODELO;
// Generated 06/09/2019 02:21:07 PM by Hibernate Tools 4.3.1
/**
 * Personal generated by hbm2java
 */
public class Producto  implements java.io.Serializable {
     private String ID_product;
     private String nombre_product;
     private String descr_product;
     private String cant_product;
     private String precio_product;
    	
    public Producto(String dniPersonal) {
        this.ID_product = ID_product;
    }
    public Producto(String ID_product, String nombre_product, String descr_product, String cant_product, String precio_product) {
       this.ID_product = ID_product;
       this.nombre_product = nombre_product;
       this.descr_product = descr_product;
       this.cant_product = cant_product;
       this.precio_product = precio_product;
    }

    public String getID_product() {
        return ID_product;
    }

    public void setID_product(String ID_product) {
        this.ID_product = ID_product;
    }

    public String getNombre_product() {
        return nombre_product;
    }

    public void setNombre_product(String nombre_product) {
        this.nombre_product = nombre_product;
    }

    public String getDescr_product() {
        return descr_product;
    }

    public void setDescr_product(String descr_product) {
        this.descr_product = descr_product;
    }

    public String getCant_product() {
        return cant_product;
    }

    public void setCant_product(String cant_product) {
        this.cant_product = cant_product;
    }

    public String getPrecio_product() {
        return precio_product;
    }

    public void setPrecio_product(String precio_product) {
        this.precio_product = precio_product;
    }
   
   



}


