package MODELO;
// Generated 06/09/2019 02:21:07 PM by Hibernate Tools 4.3.1
/**
 * Personal generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {
     private String ID_vend;
     private String nom_vend;
     private String apell_vend;
     private String correo_vend;
     private String dni_vend;
     private String usuario;
     private String password;
  	
    public Vendedor(String ID_vend) {
        this.ID_vend = ID_vend;
    }
    public Vendedor(String ID_vend, String cliente, String nom_vend, String apell_vend, String correo_vend, String dni_vend, String usuario, String password) {
       this.ID_vend = ID_vend;
       this.nom_vend = nom_vend;
       this.apell_vend = apell_vend;
       this.correo_vend = correo_vend;
       this.dni_vend = dni_vend;
       this.usuario = usuario; 
       this.password = password;  
    }

    public String getID_vend() {
        return ID_vend;
    }

    public void setID_vend(String ID_vend) {
        this.ID_vend = ID_vend;
    }

    public String getNom_vend() {
        return nom_vend;
    }

    public void setNom_vend(String nom_vend) {
        this.nom_vend = nom_vend;
    }

    public String getApell_vend() {
        return apell_vend;
    }

    public void setApell_vend(String apell_vend) {
        this.apell_vend = apell_vend;
    }

    public String getCorreo_vend() {
        return correo_vend;
    }

    public void setCorreo_vend(String correo_vend) {
        this.correo_vend = correo_vend;
    }

    public String getDni_vend() {
        return dni_vend;
    }

    public void setDni_vend(String dni_vend) {
        this.dni_vend = dni_vend;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


}


