package MODELO;
// Generated 06/09/2019 02:21:07 PM by Hibernate Tools 4.3.1



/**
 * Personal generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private String ID_venta;
     private String cliente;
     private String nom_vend;
     private String apell_vend;
     private String forma_pago;
     private String neto;
     private String total;
  

  	
    public Venta(String ID_venta) {
        this.ID_venta = ID_venta;
    }
    public Venta(String ID_venta, String cliente, String nom_vend, String apell_vend, String forma_pago, String neto, String total) {
       this.ID_venta = ID_venta;
       this.cliente = cliente;
       this.nom_vend = nom_vend;
       this.apell_vend = apell_vend;
       this.forma_pago = forma_pago;
       this.neto = neto;
       this.total = total;       
    }

    public String getID_venta() {
        return ID_venta;
    }

    public void setID_venta(String ID_venta) {
        this.ID_venta = ID_venta;
    }

    public String getCliente() {
        return cliente;
    }

    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    public String getNom_vend() {
        return nom_vend;
    }

    public void setNom_vend(String nom_vend) {
        this.nom_vend = nom_vend;
    }

    public String getApell_vend() {
        return apell_vend;
    }

    public void setApell_vend(String apell_vend) {
        this.apell_vend = apell_vend;
    }

    public String getForma_pago() {
        return forma_pago;
    }

    public void setForma_pago(String forma_pago) {
        this.forma_pago = forma_pago;
    }

    public String getNeto() {
        return neto;
    }

    public void setNeto(String neto) {
        this.neto = neto;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }      

}


